apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlet-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shortlet-api
  template:
    metadata:
      labels:
        app: shortlet-api
    spec:
      containers:
      - name: shortlet-api
        image: gcr.io/[PROJECT_ID]/flask-app
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
